name: PR deployment on astra

on:
  pull_request:
    branches: 
      - main

jobs:
    deploy-pr:
        runs-on: self-hosted
        steps:

            - uses: actions/checkout@v3

            - name: Install server dependencies
              run: npm install

            - name: Install client dependencies and build
              working-directory: client
              run: |
                npm install --legacy-peer-deps
                npm run build

            - name: Install rproxctl
              run: |
                echo "$HOME/go/bin" >> $GITHUB_PATH

            - name: Run dev server and add route to rprox
              run: |
                # Extract branch name
                BRANCH_NAME=$(echo "${{ github.head_ref }}" | tr '/' '-')

                # Find free port starting from 5000
                PORT=5000
                while ss -ltn | grep -q ":$PORT "; do
                  PORT=$((PORT + 1))
                done

                export PORT=$PORT
                export BRANCH_NAME=$BRANCH_NAME

                echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
                echo "PORT=$PORT" >> $GITHUB_ENV

                if  pm2 list | grep -q onlyfriends-$BRANCH_NAME; then
                  pm2 restart onlyfriends-$BRANCH_NAME
                else
                  pm2 start ecosystem.config.js --env development --update-env || { echo "PM2 start failed"; pm2 logs; exit 1; }
                fi

            - name: Add route to rprox
              run: |
                rproxctl -cmd set -path ${BRANCH_NAME}-onlyfriends -target http://host.docker.internal:$PORT -ttl 3600

            - name: Set Autokill after 1 hour
              run: nohup bash -c "sleep 3600; pm2 delete onlyfriends-$BRANCH_NAME" &


