name: PR deployment on astra

on:
  pull_request:
    branches: 
      - main

jobs:
    deploy-dev:
        runs-on: self-hosted
        steps:

            - uses: actions/checkout@v3

            - name: Install server dependencies
              run: npm install

            - name: Install client dependencies and build
              working-directory: client
              run: |
                npm install --legacy-peer-deps
                npm run build

            - name: Run dev server and add route to rprox
              run: |
                # Extract branch name
                BRANCH_NAME=$(echo "${{ github.head_ref }}" | tr '/' '-')

                # Find free port starting from 5000
                PORT=5000
                while ss -ltn | grep -q ":$PORT "; do
                  PORT=$((PORT + 1))
                done

                pm2 describe onlyfriends-$BRANCH_NAME > /dev/null 2>&1
                if [ $? -eq 0 ]; then
                  pm2 restart onlyfriends-$BRANCH_NAME
                else
                  PORT=$PORT BRANCH_NAME=$BRANCH_NAME pm2 start ecosystem.config.js --env development --update-env
                fi
                
                # Add route to rprox
                rproxctl -cmd set -path ${BRANCH_NAME}-onlyfriends -target http://host.docker.internal:$PORT -ttl 3600

            - name: Set Autokill after 1 hour
              run: nohup bash -c "sleep 3600; pm2 delete onlyfriends-$BRANCH_NAME" &


